### PR TITLE
Retry failed ssh commands in the ec2 python script.

### PR DESCRIPTION
**Pull request by holdenk**
This is especially useful when starting up when the hosts may not have yet come on-line but can be useful at other points for people with flakey connections

### CODE REVIEW

**Comment by mateiz** [comment]
This looks like a good thing to fix, but I'd prefer doing it just inside the "ssh" method instead of using a decorator, since we won't use this in a lot of other places, and it will make the code easier to follow. Just put a loop in there.

**Comment by holdenk** [comment]
Sounds good, I'll do that.

**Comment by holdenk** [comment]
Cool I've switched it to just be a simple loop in the script and removed the retry decorator code.

**Comment by mateiz** [comment]
Thanks, that looks great.

**Pull request merged**
