### PR TITLE
Changed CoGroupRDD's hash map from Scala to Java.

### PR DESCRIPTION
**Pull request by rxin**
Experiences with both Shark and GraphLab have shown that using the Java hashmap improved performance.

### CODE REVIEW

**Comment by mateiz** [comment]
Yes it does, I think we replaced it in other places before. Are you sure that getOrElseUpdate is fast on this though? Maybe it would be better to do map.get / map.put.

**Comment by rxin** [comment]
Yes - the Shark one uses get/put explicitly. Let me do that.

**Comment by mateiz** [comment]
By the way, for these use cases where a table just grows, we may be even better off with fastutil's Object2ObjectOpenHashMap: http://fastutil.dsi.unimi.it/docs/it/unimi/dsi/fastutil/objects/Object2ObjectOpenHashMap.html. Might be fun to try sometime. It's an array-based map so it has much fewer objects.

**Comment by rxin** [comment]
Done.

I will do the fastutil hashmap next time in a separate pull request.

**Comment by mateiz** [comment]
Great, thanks. The fastutil thing would need testing anyway to make sure it's faster. And it might be best to jump straight to our own HashMap implementation anyway (using a single Array[Object] instead of the two that fastutil has for better cache locality).

**Pull request merged**
