### PR TITLE
Use different Hadoop version for YARN artifacts.

### PR DESCRIPTION
**Pull request by pwendell**
This uses a seperate Hadoop version for YARN artifact. This means when people link against
spark-yarn, things will resolve correctly.

### CODE REVIEW

**Comment by pwendell** [comment]
Jenkins, test this please.

**Comment by pwendell** [comment]
Okay I test this locally because Jenkins hasn't recovered from the UCB power outage yet :)

**Comment by jey** [comment]
User applications don't link against `spark-yarn`, only against `spark-core`. The `spark-yarn` package is only used internally by the assembly that gets submitted to the YARN cluster.

**Comment by pwendell** [comment]
Hey @jey Some folks actually -1'd the release because we didn't publish the spark-yarn artifact, so I think somehow someone is linking against this. I don't totally understand the use case though...

**Comment by pwendell** [comment]
btw, does this interfere with the existing stuff you were working on? Or are you just suggesting it might not be necessary given the way `spark-yarn` is used.

**Comment by mateiz** [comment]
The problem wasn't as much that we didn't publish spark-yarn, but that the version in its POM was wrong because it wasn't handled by the Apache release plugin. So we do need to do this. It doesn't matter whether users link to it.

**Comment by jey** [comment]
OK. We should also update the docs to mention that YARN users now need to do `mvn -Phadoop2-yarn -Dhadoop.version=2.0.5-alpha -Dyarn.version=2.0.5-alpha package`

**Comment by pwendell** [comment]
Hey @jey  good call I just opened this PR:
https://github.com/mesos/spark/pull/931

**Comment by jey** [comment]
@pwendell, publishing it should cause no harm; just that it's not useful for anything except the `spark-assembly` target.

**Pull request merged**
