### PR TITLE
SPARK-827: MAX_TASK_FAILURES not configurable

### PR DESCRIPTION
**Pull request by dlyubimov**
Add configuration for MAX_TASK_FAILURES. 

Sometimes there's a need to adjust number of retries (such as in real time situations when the request must rather be dropped on the floor than fulfilled much later than SLA).

### CODE REVIEW

**Comment by mateiz** [comment]
Jenkins, this is ok to test

**Comment by mateiz** [comment]
Hey Dmitriy, this looks good, but I have two suggestions:
- Change the property name to spark.task.maxFailures
- Add this parameter into the table of config parameters in docs/configuration.md

**Comment by mateiz** [comment]
I've merged this manually due to a small conflict. Thanks Dmitriy!

**Comment by dlyubimov** [comment]
Don't mention it, my goals are always selfish. Thanks for developing the
awesome machine cluster tool.

**Pull request merged**
