### PR TITLE
Handle Terminated to avoid endless DeathPactExceptions.

### PR DESCRIPTION
**Pull request by stephenh**
Credit to Roland Kuhn, Akka's tech lead, for pointing out this
various obvious fix, but StandaloneExecutorBackend.preStart's
catch block would never (ever) get hit, because all of the
operation's in preStart are async.

So, the System.exit in the catch block was skipped, and instead
Akka was sending Terminated messages which, since we didn't
handle, it turned into DeathPactException, which started
a postRestart/preStart infinite loop.

### CODE REVIEW

**Comment by stephenh** [comment]
I will make no comments about how the tests may/may not be working better with this change, lest I jinx it.

**Comment by mateiz** [comment]
Got it, that makes sense. Thanks for the fix!

**Comment by mateiz** [comment]
Actually this seems to not be in sync with master -- can you rebase it? Or want me to just merge it manually?

**Comment by stephenh** [comment]
Sure, I'll merge.

**Comment by stephenh** [comment]
Cool, fixed, just some import conflicts.

**Comment by mateiz** [comment]
Alright, thanks.

**Pull request merged**
