### PR TITLE
support customized java options for Master, Worker, Executor, and Repl

### PR DESCRIPTION
**Pull request by haitaoyao**
hi,
Sometimes I need to remote debug one of the processes of spark. Or set the heap dump path to diffrent locations for each process. So I need to set different java opts for each java process in spark. So I add some code in run , and the java options can be set in conf/spark-env.sh like this:

```
export SPARK_MASTER_OPTS='-Dspark_master'
export SPARK_WORKER_OPTS='-Dspark_worker'
export SPARK_EXECUTOR_OPTS='-Dspark_executor'
export SPARK_REPL_OPTS='-Dspark_repl'
```

Hope this can be merged into trunk.
Thanks.

### CODE REVIEW

**Comment by haitaoyao** [comment]
I also change the .gitignore file to ignore ensime files. And another one is just a little fix  in javadoc.
Sorry, I forgot these two files have changed.

**Comment by mateiz** [comment]
Thanks for adding these! Do you happen to have access to a Windows machine by any chance? If so, can you also add them to the `run2.cmd` script there? If not, I'll look into that.

**Comment by haitaoyao** [comment]
well, I can not find a windows env by hand. I'm afraid I cannot work on
this.
It's my pleasure to have it merged into trunk. Iwish I can do more that
this. Thanks.
ÔÚ 2013-2-24 ÏÂÎç3:28£¬"Matei Zaharia" notifications@github.comÐ´µÀ£º

**Comment by mateiz** [comment]
Alright, thanks; we'll fix the Windows versions later.

**Pull request merged**
