### PR TITLE
Fixed path to JavaALS.java and JavaKMeans.java, fixed hadoop2-yarn profi...

### PR DESCRIPTION
**Pull request by apivovarov**
...le

### CODE REVIEW

**Comment by shivaram** [comment]
Jenkins, this is ok to test

**Comment by shivaram** [comment]
Thanks for catching this. Fixes look good to me -- Will merge them once Jenkins passes.

**Comment by apivovarov** [comment]
My pleasure. 
What you think if I change hadoop dependency from 2.0.2 to 2.0.5 in hadoop2-yarn profile in parent pom.xml?

**Comment by shivaram** [comment]
I wouldn't recommend changing the dependency in this PR. You could open another PR and I guess @mridulm or @mateiz will take a look. Also any reasons why this should be changed ?

**Comment by apivovarov** [comment]
I made a separate PR for yarn.version change https://github.com/mesos/spark/pull/806
latest hadoop-2.0.x version is 2.0.5

**Comment by rxin** [comment]
Alex, do you mind rebasing the branch, so the extra commits (the original one and the reverting one) about 2.0.2->2.0.5 don't show up on this one?

**Pull request merged**
