### PR TITLE
Hopefully fix the mesos load issues

### PR DESCRIPTION
**Pull request by mridulm**
Attempt based on the excellent work already analyzed in https://github.com/mesos/spark/pull/684
Hopefully this will circumvent the need for it.

Please do not merge yet : untested right now, requesting feedback.
If it does not work, will close.

### CODE REVIEW

**Comment by mridulm** [comment]
Please do not commit now - awaiting user test results.
If negative, will close request.

**Comment by charlesreiss** [comment]
FWIW, this doesn't fix the problem for me in a case where #684 does. If I apply your patch, configure MESOS_NATIVE_LIBRARY, start Mesos locally (one master and one slave) and run, e.g.,

./run spark.examples.SparkPi mesos://127.0.0.1:5050

then I get something like

Exception in thread "Thread-53" spark.SparkException: ClassNotFound with classloader: null
        at spark.scheduler.cluster.ClusterTaskSetManager.taskFinished(ClusterTaskSetManager.scala:526)
        at spark.scheduler.cluster.ClusterTaskSetManager.statusUpdate(ClusterTaskSetManager.scala:493)
        at spark.scheduler.cluster.ClusterScheduler.statusUpdate(ClusterScheduler.scala:422)
        at spark.scheduler.mesos.MesosSchedulerBackend.statusUpdate(MesosSchedulerBackend.scala:238)
Caused by: java.lang.ClassNotFoundException: spark/scheduler/TaskResult
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at spark.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:20)  
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1593)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1514)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1750)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:369)
        at spark.JavaDeserializationStream.readObject(JavaSerializer.scala:23)
        at spark.JavaSerializerInstance.deserialize(JavaSerializer.scala:39)
        at spark.scheduler.cluster.ClusterTaskSetManager.taskFinished(ClusterTaskSetManager.scala:520)
        ... 3 more

Running the same scenario on top of #684 completes normally.

**Comment by mridulm** [comment]
This is weird result ... since the exception is unrelated to mesos or the
change introduced.

Regards
Mridul

**Comment by andrewmilkowski** [comment]
Gentlemen ... it is looking good...

applied both paches

https://github.com/mesos/spark/pull/684

and

https://github.com/mesos/spark/pull/690

using latest master mesos and spark, test ran successful wheer test is a simple filter on a small data set

also (but this was given as shark uses spark) ran successful shark test on mesos

best regards

**Comment by andrewmilkowski** [comment]
guarantee yourselves this: clean dev env by cleaning .m2/repository .ivy/cache .ivy2/cache any .target dirs any CLASSPATH that could point to old version of libs and rebuild spark rebuild test program from the ground up... 

very best

**Comment by andrewmilkowski** [comment]
on the record

690 by itself is insufficient ( spark.SparkException: ClassNotFound with classloader: null is thrown) one needs to apply 684 (https://github.com/mesos/spark/pull/684) as well

best regards

**Comment by mridulm** [comment]
Looks like this does not solve the issue in a principled way ... so we will need to rely on #684 for now.
Unfortunately, that means if there are other code paths which interact with mesos, we will simply have to revisit the issue again, sigh.

Closing this PR.

**Comment by mateiz** [comment]
Sounds good. Maybe we can get some help from Mesos on this in future versions.

**Pull request closed without merging**
