### PR TITLE
Shuffle Performance Optimization

### PR DESCRIPTION
**Pull request by shane-huang**
The patch includes below optimizations for shuffle performance. 
1. Use netty embeded OIO file server instead of Connection Manager for block shuffling.
2. Skip 0-byte block requests to reduce the network transport in shuffle

A system property "spark.shuffle.use.netty" is provided for user to choose whether enable or disable this optimization.  If spark.shuffle.use.netty=true, the optimization is enabled, otherwise it is disabled. By default it is disabled. 

This patch is moved from against branch-0.6 to master. The original pull request is closed( https://github.com/mesos/spark/pull/522).

### CODE REVIEW

**Comment by shane-huang** [comment]
Still got issues running sbt test on master as discussed in https://groups.google.com/forum/?fromgroups=#!topic/spark-users/G__mvv0w_bk . Anyway I've compared the number of passed cases w/ and w/o the patch, they're the same. Could anyone whose sbt test works fine help run sbt test again to verify this patch? Thanks very much.

**Comment by massie** [comment]
Jenkins, add to whitelist and test this please.

**Comment by massie** [comment]
All tests passed.

**Comment by shane-huang** [comment]
I've got my hands full these days and don't have time to minimize the java implementations as @rxin suggested in thread https://github.com/mesos/spark/issues/522. Are you guys fine with the current status? If it's urgent, we may have to find someone else to do the minimization. If not, I'll move all java implementation into scala after scala 2.10 support is available.

**Comment by mateiz** [comment]
No worries, maybe we'll handle this on our end. It would be nice to get it in 0.7 as well.

**Comment by shane-huang** [comment]
I just found a bug in the netty implementation running with master. Please kindly pend the code merge until I fix it. Sorry for the inconvenience.

**Comment by mateiz** [comment]
Alright, no worries. I'm still traveling a bunch so unfortunately it's been tough to find time to look at it, but I'll finish with all the traveling next week.

**Comment by shane-huang** [comment]
fixed the bug in netty block fetcher and passed local test.

**Comment by mridulm** [comment]
I am curious what the performance difference now is .. given recent performance enhancements merged into master.

Regards,
Mridul

**Comment by mateiz** [comment]
Hey Shane, just an update on my side -- we're currently debugging some issues caused by an earlier merge (https://github.com/mesos/spark/pull/575), but once that's done, I'm going to add this pull request in as well (I can manually handle the update to work with Mridul's code). So it hasn't been forgotten! I hope to get to it very soon, but I've just had a lot of other stuff to do.

**Comment by rxin** [comment]
Hi Shane,

Thanks a lot for doing this!

I did a manual merge of your code and some cleanups. This is now in #602 . I am going to close this one.

**Pull request closed without merging**
