### PR TITLE
Fix issue with spark_ec2 seeing empty security groups

### PR DESCRIPTION
**Pull request by aarondav**
Under unknown, but occasional, circumstances, reservation.groups is empty
despite reservation.instances each having groups. This means that the
spark_ec2 get_existing_clusters() method would fail to find any instances.
To fix it, we simply use the instances' groups as the source of truth.

Note that this is actually just a revival of PR #827, now that the issue
has been reproduced.

### CODE REVIEW

**Comment by pwendell** [comment]
Thanks Aaron, also thanks @lucarosellini who originally reported this.

**Comment by JoshRosen** [comment]
It sounds like this may fix [SPARK-749](https://spark-project.atlassian.net/browse/SPARK-749), a similar issue that I ran into once but had trouble reproducing.

**Comment by lucarosellini** [comment]
@pwendell @ilikerps 
Using a patch very similar to what has been merged, in certain circumstances I got duplicate entries in "master_nodes" and "slave_nodes". 
That's why I had to add commit bf693d41ff87dd23565db64b3f23fe59164cd605 to the original pull request #827.
During the next days I'll try to reproduce the problem and I'll let you know.

**Comment by aarondav** [comment]
@lucarosellini 
I believe you ran into that issue because you were appending res.instances for every instance -- that is, you were adding every instance in a reservation len(res.instances) times. We should now avoid this by simply appending "inst" instead of "res.instances".

**Comment by aarondav** [comment]
@JoshRosen 
SPARK-749 definitely looks like the same issue, or at very least the same solution. I'll mark it as resolved if you have no objections.

**Comment by pwendell** [comment]
Ya lets resolve SPARK-749 seems like the same thing.

**Comment by lucarosellini** [comment]
@ilikerps yes, you're right, I missed that. Thank you.

**Pull request merged**
