### PR TITLE
Netty and shuffle  bug fixes

### PR DESCRIPTION
**Pull request by shivaram**
This patch fixes some bugs in the recent netty shuffle refactoring. This also fixes a DiskBlockObjectWriter bug where some blocks were reported to have zero size when using kryo. Thanks to @jey for catching this and @rxin for various suggestions.

### CODE REVIEW

**Comment by mateiz** [comment]
Jenkins: this is ok to test.

**Comment by rxin** [comment]
To provide a little bit more context, there are three problems this pull request solved:
1. Our previous unit tests didn't actually test the Netty shuffle code path because it was starting a local cluster with 1 process (2 cores) instead of 2 processes (1 core/each). There was no cross-process shuffle block fetches at all ...
2. The Netty FileServer gets started, and then immediately shut down. This pull request fixes that too.
3.  BlockObjectWriter's commit method doesn't force the serializer to flush before checking the size. This works fine for Java, but would fail for Kryo because Kryo manages its own output buffer.

**Comment by shivaram** [comment]
I also updated `revertPartialWrites` to similarly flush the serializer when we have a task failure.

**Comment by rxin** [comment]
Jenkins: this is ok to test.

Jenkins: test this please.

Jenkins: test this again please.

**Comment by jey** [comment]
Jenkins, retest this please.

**Comment by rxin** [comment]
Is that the magic word? :)

**Comment by rxin** [comment]
Actually since this no longer merges, it doesn't make sense for Jenkins to run the test. Shivaram will update the pr to do the merge.

**Comment by shivaram** [comment]
Fixed the merge. I am also running tests locally right now

**Comment by rxin** [comment]
Thanks!

**Pull request merged**
