### PR TITLE
Update Maven build to Scala 2.9.3

### PR DESCRIPTION
**Pull request by jey**
This patch applies Andy's sbt changes in 5555811bd54ddb84bce11d4ab04b1f818c221a14 to the Maven build

### CODE REVIEW

**Comment by mateiz** [comment]
Thanks for the patch.

**Comment by jey** [comment]
Please apply this to `master` as well

**Comment by jey** [comment]
Matei, could you please apply this to the `master` branch?

**Comment by rxin** [comment]
I will cherry pick that into master.

**Comment by rxin** [comment]
Jey - are these warning messages expected?

[INFO] --- scala-maven-plugin:3.1.0:doc-jar (attach-scaladocs) @ spark-examples ---
[WARNING]  Expected all dependencies to require Scala version: 2.9.3
[WARNING]  com.twitter:algebird-core_2.9.2:0.1.11 requires scala version: 2.9.2
[WARNING] Multiple versions of scala libraries detected!
[WARNING]  Expected all dependencies to require Scala version: 2.9.3
[WARNING]  com.twitter:algebird-core_2.9.2:0.1.11 requires scala version: 2.9.2
[WARNING] Multiple versions of scala libraries detected!

**Comment by jey** [comment]
Yes, unfortunately that's just the current state of the Scala landscape.

**Pull request merged**
