### PR TITLE
Examples ship to to cluster

### PR DESCRIPTION
**Pull request by dennybritz**
- Fixes #118
- I wasn't sure how to best get the path to the example JAR, I didn't want to do it manually in every examples. I added another variable in the ./run script that's being used by the examples. Let me know if that's not the best way.
- Should update the example documentation to tell people to run "sbt/sbt package" before running the examples.

### CODE REVIEW

**Comment by mateiz** [comment]
This looks good, but can you also update the README to say that you should run sbt package instead of sbt compile? Otherwise the examples JAR won't get built. Also, rename the EXAMPLES_JAR variable to SPARK_EXAMPLES_JAR so that it doesn't conflict with other environment variables the user might make.

**Comment by mateiz** [comment]
Hey Denny, not sure if you saw my comment here, but can you rename the environment variable as mentioned above, and update the README to say sbt package? Otherwise it looks good.

**Comment by dennybritz** [comment]
I made the changes you suggested.

**Comment by mateiz** [comment]
Great, thanks!

**Pull request merged**
