### PR TITLE
Added pairing to ec2 script.

### PR DESCRIPTION
**Pull request by itaibenari**
added utility for allowing access from local to master on the spark port, enabling shell connection to master.

### CODE REVIEW

**Comment by JoshRosen** [comment]
Does this actually let you run jobs against the remote master?  I'm pretty sure that this won't work because Spark uses additional ephemeral ports for other components, and also because your driver might be behind a firewall that prevents the master from connecting back to it.  See https://groups.google.com/d/msg/spark-users/fI-873l2edY/Ds0snjezShEJ

**Comment by itaibenari** [comment]
It wouldn't work for a client machine not accessible to the slaves. Another requirement seems to be that the directory structure on the client needs to mimic the one on the cluster nodes (/root/spark) which may be achieved by an additional step of soft linking. I agree these restrictions limit the usability of this feature.

**Comment by JoshRosen** [comment]
Since that's the case, I'm against merging this pull request.  I think that it doesn't provide much value and will confuse users.  If you want a quick way to add the current machine to the master's EC2 security group, you can use `ec2-authorize` from the [EC2 API tools](http://aws.amazon.com/developertools/351):

```
ec2-authorize $CLUSTERNAME-master -P tcp -p 7077 -s `curl http://whatismyip.akamai.com/`/32
```

**Comment by itaibenari** [comment]
understandable

**Pull request closed without merging**
