### PR TITLE
Eliminate CacheTracker

### PR DESCRIPTION
**Pull request by charlesreiss**
Replaces DAGScheduler's queries of CacheTracker with BlockManagerMaster
queries. This may have negative performance implications; I have not tested for them.

The remaining CacheTracker functionality of locally coordinating the computation of cachable RDDs is moved to a new class called CacheManager.

### CODE REVIEW

**Comment by mateiz** [comment]
Regarding efficiency -- it may be worth optimizing BlockManagerMasterActor.getLocationsMultipleBlockIds for this. When creating the ArrayBuffer to return, give it the locations directly instead of making a (likely size 16) empty one and then calling appendAll. Or even better, it might be possible to return an array. The whole blockLocations data structure is a bit scary in terms of memory usage unfortunately; a bunch of HashSets in there seems like overkill.

**Comment by mateiz** [comment]
One other comment: I think you forgot to git add CacheManager.scala.

**Comment by charlesreiss** [comment]
I indeed forget to add CacheManager.scala; fixed.

**Comment by mateiz** [comment]
Alright, thanks.

**Pull request merged**
