### PR TITLE
Scala 2.10 master merge

### PR DESCRIPTION
**Pull request by ScrapCodes**
There are a few test failing of which, one is new. 
spark.streaming.CheckpointSuite [Fixed now]

Other test failing, which also fail on master.
spark.DriverSuite
spark.DistributedSuite 
spark.FileServerSuite

### CODE REVIEW

**Comment by markhamstra** [comment]
I just quickly walked through the diff between what you've got and what I had done in https://github.com/markhamstra/spark/tree/master-2.10 (and which I am in the process of syncing back up with master.)

Except for your recent changes to the repl, I think I'm strictly ahead of where you are at, and have done considerable work in changing from Manifests to ClassTags, fixing other deprecations and warnings, etc.  Once I get done bringing mine back into sync with master, I think we'd be better off if you base your recent changes off my master-2.10 instead of directly off master.

UPDATE: Okay, I'm back in sync with master.

**Comment by ScrapCodes** [comment]
@markhamstra That is really nice. My take of problem was to solve warnings in a different pull request. There are a few subtle things that, I have done related to changing dependency of zeromq. I just wish, I knew about your branch. So may be you can send those as a seperate pull request, that way it would be easier for others to review !

**Comment by ScrapCodes** [comment]
The only broken test is fixed. 

@tdas Just wanted to ask, if there was a particular reason, for which you were using RichInt in streaming.CheckpointSuite ?

@markhamstra I have tried to build from your repo, there were a few warnings etc.. yet to be fixed. Also you might want to fix unused imports. I just wanted to know, will it be easy for you to apply your changesets on this branch? Incase not, I don't mind rebasing it.

**Comment by markhamstra** [comment]
Sorry that you ended up duplicating some work.  I mentioned my master-2.10 branch on the Spark Users list a couple of times, but I guess you must have missed it.  Yet another example of how we need better communication and coordination among the growing number of Spark contributors.

I'm not going to get a chance to look at this again for at least a couple of days; but if you want to give it a go, I don't think that rebasing your later work against my branch should be too difficult.  I've already got your earlier repl work in my branch, and most of the rest of the changes there should be orthogonal.  I've also got a separate pull request dealing with unused imports: https://github.com/mesos/spark/pull/520 -- I'll sync that back up with master in a minute.

**Comment by ScrapCodes** [comment]
It is ready to go. I suppose.

**Comment by onsails** [comment]
Wow thanks, @ScrapCodes! We will test it in our project this week.

**Comment by ScrapCodes** [comment]
@wishbear Thats great ! Feel free to come back with suggestions or if you need any help. Thanks !

@markhamstra I found it easy to look at your changes and then applying on my branch than rebasing. So thats what I did. Not sure if that was the right thing ! but easiest perhaps.

**Comment by mateiz** [comment]
Thanks for the update, Prashant! I've now merged this. I did a few fixes to deal with the failing tests (which are due to Akka 2.1) -- see https://github.com/mesos/spark/commit/5b5b5aedbf01c84e49da884f361c1ca87f410628 -- but unfortunately, there's still a failure in DriverSuite because Akka now creates a non-daemon Netty thread even run in daemon node. That kind of sucks but there's not much we can do.

I hope to merge this with further changes from master in the next few weeks so we can eventually bring it into 0.8 or 0.9. There's been some action in master but I think this PR dealt with most of the issues that would come up. It's just these library dependency ones that are annoying.

**Comment by ScrapCodes** [comment]
Thanks Matei! bringing it into 0.8 would be great. I saw DriverSuite hanging too, will try to check it out(I have very less hope though ).

**Pull request merged**
