### PR TITLE
fix a bug of using wildcard in make-distribution.sh; ask sbt to check local maven repo in SparkBuild.scala

### PR DESCRIPTION
**Pull request by Du-Li**
fixed a wildcard bug in make-distribution.sh:
         move the wildcard out of the quotes

ask sbt to check local maven repo in SparkBuild.scala:
       sbt uses ivy which by default only checks ~/.ivy2. need to tell sbt to also check ~/.m2 because mesos make maven-install only publishes to ~/.m2

### CODE REVIEW

**Comment by Du-Li** [comment]
Sorry for the mess. I was trying to create one pull request for each of the two latest fixes I made. But it somehow combined many irrelevant commits, which is not what I intended.

**Comment by hsaputra** [comment]
Hi Du,

Would you mind filing the pull request to the Apache Spark repo instead

Thx,

Henry

**Comment by Du-Li** [comment]
Sure. Will do today.

Du

**Comment by Du-Li** [comment]
done

**Pull request closed without merging**
