### PR TITLE
Updated Kryo to version 2.20

### PR DESCRIPTION
**Pull request by rxin**
sbt/sbt test pass.

Tried it on Shark using a join query that produces 60 million rows and it worked fine. Saw a negligible performance increase in the join query (very hard to tell the difference - if anything, ~ 5% - could well be just system variability even though I tested 20 times).

### CODE REVIEW

**Comment by mateiz** [comment]
Cool, that was fast! Let me figure out the branches a bit before merging this though. I want to keep branch 0.6 on Kryo 1.x, and then merge dev into master and have that take in this stuff.

**Comment by rxin** [comment]
BTW - I run Shark with Kryo 2.0 through all 700 tests, and only 4 of them failed because of the following reason:

spark.SparkException: Job failed: ShuffleMapTask(2236, 0) failed: ExceptionFailure(com.esotericsoftware.kryo.KryoException: java.lang
.IllegalArgumentException: Can not set java.sql.Timestamp field org.apache.hadoop.hive.serde2.io.TimestampWritable.timestamp to java.
util.Date
Serialization trace:
timestamp (org.apache.hadoop.hive.serde2.io.TimestampWritable)
value (org.apache.hadoop.hive.serde2.objectinspector.primitive.WritableConstantTimestampObjectInspector)
fieldObjectInspector (org.apache.hadoop.hive.serde2.objectinspector.StandardStructObjectInspector$MyField)
fields (org.apache.hadoop.hive.serde2.objectinspector.StandardStructObjectInspector)
array (scala.collection.mutable.ArrayBuffer))

I will look into this. Other than that, this looks pretty solid.

**Comment by mateiz** [comment]
Not bad. I assume the Spark tests pass too?

Matei

**Comment by rxin** [comment]
That was in the original comment: sbt/sbt test passes :)

**Comment by rxin** [comment]
I was able to fix the problem with TimestampWritable in Shark by creating a new specialized serializer for writables:

``` scala

    kryo.register(classOf[org.apache.hadoop.hive.serde2.io.TimestampWritable],
      new KryoWritableSerializer[org.apache.hadoop.hive.serde2.io.TimestampWritable])


/** A Kryo serializer for Hadoop writables. */
class KryoWritableSerializer[T <: Writable] extends KSerializer[T] {
  override def write(kryo: Kryo, output: KryoOutput, writable: T) {
    val ouputStream = new DataOutputStream(output)
    writable.write(ouputStream)
  }

  override def read(kryo: Kryo, input: KryoInput, cls: java.lang.Class[T]): T = {
    val writable = cls.newInstance()
    val inputStream = new DataInputStream(input)
    writable.readFields(inputStream)
    writable
  }
}
```

**Comment by mateiz** [comment]
Reynold, I want to merge this into the master brach, but can you try it with Shark first to make sure it's still okay?

**Comment by rxin** [comment]
Will do tomorrow.

**Comment by rxin** [comment]
Hey Matei - you can merge this now.

**Comment by mateiz** [comment]
Alright, great!

**Comment by mateiz** [comment]
Hey Reynold, does the documentation on using a custom KryoRegistrator need to change now?

**Pull request merged**
