### PR TITLE
STREAMING-51: Add RDD type as a type parameter in JavaDStreamLike

### PR DESCRIPTION
**Pull request by pwendell**
This patch adds the JavaRDD type as a type parameter to JavaDStreamLike. That change simplifies some repeated code between JavaDStream and JavaPairDStream. The patch adds tests to verify new functionality. There is some more detail in individual commits.

### CODE REVIEW

**Comment by tdas** [comment]
Hey Patrick, I updated the streaming branch with a massive update. However, I see that this pull request can still be merged, which I find a little suspicious. Can you please pull the latest changes, and compile and run the tests to confirm that everything passes?

Also, I just remembered something I missed. I forgot to add twitterStream to the Java StreamingContext. Can you do that? Should be a small change.

Thanks

**Comment by pwendell** [comment]
TD - this request is against the master branch. Earlier Matei reviewed and
committed some smaller changes to master. which branch should I be
submitting small changes to? I expect that I'll make several smaller
changes like this going forward. I'm fine either way.
- Patrick

**Comment by pwendell** [comment]
Regarding the Java twitter stream - happy to take care of that, but let's do it in another pull request. Could you create a JIRA and assign it to me?

**Comment by pwendell** [comment]
I added a separate pull request to the stremaing/ branch and also tested it. If you want to merge that one, go ahead and close this one.

**Comment by tdas** [comment]
Aah, I missed the fact that this was against the master branch. Let me take a look at the other pull request.

**Pull request closed without merging**
