### PR TITLE
Remove spark-repl's extraneous dependency on spark-streaming

### PR DESCRIPTION
**Pull request by jey**
Per Reynold's request, this patch removes the extraneous dependency `spark-repl` has on `spark-streaming`, which was causing problems in Shark.

This is for `branch-0.7`.

### CODE REVIEW

**Comment by rxin** [comment]
Thanks, Jey.

To add some context:

spark-streaming introduces dependency on a version of zookeeper that is different from the version of zookeeper Hive uses. It leads to problems in Shark.

The repl binary itself doesn't really need to depend on the streaming project. spark-shell should, but that's simply a classpath setup in the run script.

**Comment by jey** [comment]
BTW -- I'm ready to release 0.7.1 once this is approved/merged.

**Comment by mateiz** [comment]
Please don't release anything or post a final version to Maven until I can take a look. We also need to fix that SBT issue.

**Comment by tdas** [comment]
Also, I have a few streaming related pull requests that have been accepted
in the streaming branch, but is yet to be pulled into the master branch. I
think they should be in the 0.7.1 release.

**Comment by mateiz** [comment]
TD, we can also include them in 0.7.2. I guess you missed the discussions on 0.7.1 when you were away. If they are small though please send a pull request to branch-0.7.

**Comment by tdas** [comment]
Aah, okay. Then I will probably hold them off. They are not super
important. They just make the kafkaStream slightly better.

TD

**Comment by mateiz** [comment]
I plan to do 0.7.2 soon after 0.7.1 with some perf fixes, so it shouldn't be a long wait.

**Comment by mateiz** [comment]
Thanks for the patch, Jey. Committed it.

**Pull request merged**
