### PR TITLE
Bootstrap redesign

### PR DESCRIPTION
**Pull request by karenfeng**
This changes the colors of the Bootstrap CSS to fit Amplab's theme colors and fixes the log paging buttons to use the Bootstrap component.
screen shot 2013-07-31 at 3 58 32 pm
screen shot 2013-07-31 at 3 58 14 pm
screen shot 2013-07-31 at 4 05 51 pm

### CODE REVIEW

**Comment by mateiz** [comment]
Hey Karen, instead of creating a custom color theme, can you just use this: http://bootswatch.com/spacelab/#? I don't think we necessarily want to reflect the AMP Lab colors. We just want something simple that isn't the default.

**Comment by karenfeng** [comment]
Ok! Here's what it looks like.
screen shot 2013-08-01 at 11 18 17 am
screen shot 2013-07-31 at 4 41 51 pm

**Comment by karenfeng** [comment]
It seems like the new font is making the rows less compact.
screen shot 2013-08-01 at 12 53 27 pm
screen shot 2013-08-01 at 11 49 53 am

**Comment by karenfeng** [comment]
screen shot 2013-08-01 at 1 28 22 pm

**Comment by karenfeng** [comment]
screen shot 2013-08-01 at 2 19 36 pm
screen shot 2013-08-01 at 2 17 29 pm

**Comment by karenfeng** [comment]
screen shot 2013-08-01 at 2 37 04 pm
screen shot 2013-08-01 at 2 41 34 pm

**Comment by karenfeng** [comment]
screen shot 2013-08-01 at 2 56 42 pm
screen shot 2013-08-01 at 2 56 37 pm

**Comment by karenfeng** [comment]
screen shot 2013-08-01 at 3 10 02 pm

**Pull request closed without merging**
