### PR TITLE
Unpersist More block manager cleanup.

### PR DESCRIPTION
**Pull request by rxin**
Implemented a removeRdd method in BlockManager, and use that to
implement RDD.unpersist. Previously, unpersist needs to send B akka
messages, where B = number of blocks. Now unpersist only needs to send W
akka messages, where W = the number of workers.

This commit was based on https://github.com/mesos/spark/pull/633 so please merge that one first.

### CODE REVIEW

**Comment by rxin** [comment]
@woggling can you take a look at this, since you have been poking block managers.

**Comment by charlesreiss** [comment]
This looks okay to me. I'd prefer it if we didn't have potential (but rare for "good" usage of unpersist()) master/worker inconsistencies, but it doesn't seem like there's a simple fix that doesn't have likely performance issues. It would also be preferable if the master tracked block groups so it didn't have to scan the entire list to find them, but that should be another patch.

**Comment by rxin** [comment]
@woggle I incorporated your comments.

**Comment by charlesreiss** [comment]
LGTM.

**Comment by mateiz** [comment]
This looks good to me too. Going to merge it.

**Pull request merged**
