### PR TITLE
For standalone mode, add worker local env setting of SPARK_JAVA_OPTS as ...

### PR DESCRIPTION
**Pull request by shane-huang**
...default and let application env override default options if applicable

I think SPARK_JAVA_OPTS should be obtained not only from application env, but also from worker's local settings. Sometimes different worker machines have different hardware configurations and we have to enable specific JVM options for certain workers instead of using the same settings for all. I suggest we use worker's local setting as default and let application settings override the worker's setting if applicable. 

Signed-off-by: shane-huang shengsheng.huang@intel.com

### CODE REVIEW

**Comment by mateiz** [comment]
Shane, I'm curious, what's a use case for this? I think that at the very least you should only add in workerLocalOpts if userOpts is not set, because otherwise they might not be compatible. I'm afraid that a user will accidentally configure one thing on their cluster (e.g. Netty shuffle) and another thing on their job, and get processes that can't talk to each other.

**Comment by mateiz** [comment]
Jenkins, this is ok to test

**Comment by shane-huang** [comment]
Since JVM allows command line options overriding and userOpts comes after workerLocalOpts, the options set in userOpts will override those set in workerLocalOpts (the “defaults”). I can barely think of any incompatible issues. Do you have an example when this way leads to incompatible issues?

An example to justify this pull request is that we may need different settings for spark.local.dir on different workers if some workers have less spindles than others. Also, sometimes we may need to install certain profiling tool on only one of the workers and add specific JVM options to collect traces.

To make it more general, I think some options are meant to be set by application users, while some options are admin-level options that are not supposed to be set by application users – actually application users may not even know how many spindles and what the folder permissions are on each cluster node. We’d better draw a line between options for users and those for administrators

Bringing the topic to the next level, I think we should make a clean separation between the functionalities for application developer/user and platform administrator. Our customers often complain that it’s not clear which scripts/options are used by application users and which are used by administrators. The current “run” script in spark home directory by default uses SPARK_MEM as heap size and it’s not suitable to run user applications if not changed or configured, so we write our own “run” scripts to run applications. You must know that Hadoop already separates the scripts used by admins and users in different folders (sbin and bin). I think this problem is practical. I’m now working to find a decent way to do the separation in spark and will later post a proposal for discussion on mailing list.

**Comment by mateiz** [comment]
Okay, that does makes sense. I was worried that with some options, like -Dspark.serializer=spark.KryoSerializer, this would cause nodes to be unable to talk to each other, if one node has the option and one doesn't. But because of the local directory for example, it may make sense to do this. Can you add one thing though -- edit spark-env.sh.template and write there that SPARK_JAVA_OPTS is only for node-specific options there, whereas app-specific ones should be set in the application?

This question of user vs admin settings will also need to be taken into account when we add a "real" configuration system to Spark instead of Java system properties (https://spark-project.atlassian.net/browse/SPARK-544). Maybe you can put together your proposal based on that. Also, I do like the idea of separating bin and sbin, and in fact I'd be happy to drop "run" also to make that less confusing.

**Comment by mateiz** [comment]
Thanks for changing the spark-env.sh too. Going to merge this.

**Pull request merged**
