### PR TITLE
Bug fix: SPARK-837

### PR DESCRIPTION
**Pull request by BlackNiuza**
[SPARK-837](https://spark-project.atlassian.net/browse/SPARK-837): ResultTask's serialization forget about handling "generation" field, while ShuffleMapTask does

### CODE REVIEW

**Comment by mateiz** [comment]
Jenkins, this is ok to test

**Comment by mridulm** [comment]
Oh my, this is serious ! Thanks for fixing it !

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by mateiz** [comment]
Looks good, thanks.

**Pull request merged**
