### PR TITLE
Clean-up of Metrics Code/Docs and Add Ganglia Sink

### PR DESCRIPTION
**Pull request by pwendell**

### CODE REVIEW

**Comment by pwendell** [comment]
Jenkins, test this please.

**Comment by pwendell** [comment]
I still need to update a few of the tests, but any feedback is welcome.

**Comment by mateiz** [comment]
Jenkins, retest this please

**Comment by pwendell** [comment]
Okay I'm good to go with this on my end. I tested this against an actual Ganglia cluster on ec2 and it seemed to work well.

**Pull request merged**
