### PR TITLE
Remove -optimize from compiler flags

### PR DESCRIPTION
**Pull request by mateiz**
According to several reports (e.g. http://stackoverflow.com/questions/6704233/what-does-the-optimise-scala-compiler-flag-do), this flag doesn't do a lot in practice, and indeed on our own performance benchmarks (http://github.com/amplab/spark-perf) it makes no difference. Removing it makes the build about 50% faster.

### CODE REVIEW

**Comment by markhamstra** [comment]
The optimizer in 2.11.x will be quite a bit different, though, so we should remember to re-evaluate this issue once Spark is using those Scala versions.

**Comment by mateiz** [comment]
Yeah, we'll definitely revisit it for 2.11.

**Comment by pwendell** [comment]
I saw zero difference in the regression tests so I'm +1 to remove this. Looks like it needs to be brought up to date though.

**Comment by wannabeast** [comment]
I have seen the flag optimize the Java byte code, in Spark, but I can't recall where. The JIT compiler may be performing the same optimization, keeping you from seeing any performance difference. It's probably visible as a reduction of the JAR size.

**Comment by mateiz** [comment]
I see, IMO let's wait until 0.8.1 then. No point doing this right now. But I do like the idea of reducing the JAR file size.

**Comment by wannabeast** [comment]
It could increase the JAR size, too, like if it does loop unrolling. You'd just have to check it.

I remember now where I saw its effect: I was looking to improve performance of your `AppendOnlyMap` by extracting common subexpressions like `2 * pos`, but I found that `-optimise` did that already, putting it into a (JVM) local variable.

**Comment by aarondav** [comment]
(We're now on the 0.8.1 branch so I vote to merge this as soon as convenient, because build times are pretty annoying right now.)

**Comment by rxin** [comment]
Submitted a new pull request to the asf git repo: https://github.com/apache/incubator-spark/pull/17

**Pull request closed without merging**
