### PR TITLE
SPARK-624: make the default local IP customizable

### PR DESCRIPTION
**Pull request by mbautin**
It would be great to be able to specify the default local IP for Spark to run servers on. This way we would not have to modify /etc/hosts on our servers (we have reasons not to). https://spark-project.atlassian.net/browse/SPARK-624

### CODE REVIEW

**Comment by mateiz** [comment]
Actually do you mind renaming this to just SPARK_LOCAL_IP? Seems a bit shorter if this is a thing that people will have to configure often.

**Comment by mbautin** [comment]
Matei: I've updated the environment variable name to be SPARK_LOCAL_IP.

**Comment by mateiz** [comment]
Great, thanks!

**Comment by mbautin** [comment]
Matei: could you also merge this into 0.6, or should I open a separate pull request? Thanks!

**Comment by mateiz** [comment]
I've merged them myself. They'll appear in the next minor version.

**Pull request merged**
