### PR TITLE
SPARK-626: Remove security groups properly

### PR DESCRIPTION
**Pull request by pas256**
SPARK-626: Remove rules before removing security groups, with a pause in between so wait for AWS eventual consistency to catch up.

### CODE REVIEW

**Comment by mateiz** [comment]
In that case, can you make deleting the groups an option, and make it off by default? I don't want all users to wait 30 seconds to turn off the cluster. The ones that want this feature can add in the option.

**Comment by pas256** [comment]
Yes I can.

**Comment by pas256** [comment]
It turns out this is far more error prone than I first though. There are multiple dependencies in play:
- dependencies between rules in security groups
- instances may not have been terminated completely when trying to delete a security group
- AWS back-end eventual consistency
- group.revoke() returns True even when it fails

The unfortunate result is the code is somewhat messy. This is as clean as I can make - there are 3 retries to delete the all groups, and exceptions are caught.

By default, groups will not be deleted, so most people won't experience this. You can delete groups when destroying a cluster by adding `--delete-groups`

**Comment by mateiz** [comment]
Okay, thanks a lot for adding this! Looks good.

**Pull request merged**
