### PR TITLE
Allow PySpark to run on Windows

### PR DESCRIPTION
**Pull request by mateiz**
This wasn't as bad as I thought; it required launching the workers directly to avoid the heavy use of UNIX features in daemon.py, and avoiding one Windows-incompatible API in java_gateway.py.

To test this, all you have to do is put python.exe on your PATH in Windows.

### CODE REVIEW

**Comment by mateiz** [comment]
Jenkins, retest this please

**Comment by mateiz** [comment]
Jenkins, retest this please

**Comment by naven084k** [comment]
Hi,

I have built spark assembly jar with java 6 using make-distribution.sh and started spark cluster on 2 nodes(which are on unix boxes)

I am able to execute java programs on the cluster.

Now I am able  to connect to the cluster from my windows machine using pyspark interactive shell

Bin> pyspark –master spark://master:7078

And then I am trying to execute following commands at interactive shell

lines = sc.textFile("hdfs://master/data/spark/SINGLE.TXT")
lineLengths = lines.map(lambda s: len(s))
totalLength = lineLengths.reduce(lambda a, b: a + b)

It is throwing the error. 

Error from python worker:
  python: module pyspark.daemon not found
PYTHONPATH was:
  /home/npokala/data/spark-install/spark-java-1.6/spark-master/python:/home/npokala/data/spark-install/spark-java-1.6/spark-master/python/lib/py4j-0.8.2.1-src.zip:/home/npokala/data/spark-install/spark-java-1.6/spark-master/assembly/target/scala-2.10/spark-assembly-1.3.0-SNAPSHOT-hadoop2.4.0.jar:/home/npokala/data/spark-install/spark-java-1.6/spark-master/sbin/../python/lib/py4j-0.8.2.1-src.zip:/home/npokala/data/spark-install/spark-java-1.6/spark-master/sbin/../python:
java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.spark.api.python.PythonWorkerFactory.startDaemon(PythonWorkerFactory.scala:163)
        at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:86)
        at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:62)
        at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:102)
        at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:70)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:265)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:232)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
        at org.apache.spark.scheduler.Task.run(Task.scala:56)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Is there any pyspark daemons do I need to start on cluster or am I missing something else.

**Comment by JoshRosen** [comment]
Hi @naven084k,

A two-year-old pull request isn't the best / most effective place to ask for help.  Instead, please post a question to the Spark user mailing list: https://spark.apache.org/community.html

**Pull request merged**
