### PR TITLE
Explicitly set class loader for MesosSchedulerDriver callbacks.

### PR DESCRIPTION
**Pull request by charlesreiss**
I think this fixes the issue where people saw ClassNotFoundExceptions from MesosSchedulerBackend.statusUpdate when running Spark master against Mesos. MesosSchedulerBackend callbacks are called from a thread which uses the default ClassLoader rather than inheriting the ClassLoader from the thread from which the scheduler backend is started.

### CODE REVIEW

**Comment by mateiz** [comment]
I see, interesting. Is there any way to test this? I guess it might be tough except when users are putting their own code on the classpath.

**Comment by charlesreiss** [comment]
I managed to get the ClassNotFoundException (and make it apparently go away with this patch) from 'MASTER=mesos://127.0.0.1:5050 ./spark-shell' (running mesos locally and pointing MESOS_NATIVE_LIBRARY to a trunk libmesos.so).

**Comment by mridulm** [comment]
Changing the classloader in the callbacks, and then letting it escape back to the pool can be unintended sideeffects.
Not to mention, other pools which might be used (and not hitting mesos driver) will 'miss' on the classloader change.
Probably the reason why someone else mentioned a failure in user group after this patch too ...

Either the classloader must be set 'properly' elsewhere before the pools are bootstrapped : so that all threads share the right loader : or, if we are continuing with this hack, at the bare minimum we should reset the classloader back to what it was before exiting the callback. It wont solve the problem as such based on comment above, but atleast wont cause other issues.

**Comment by charlesreiss** [comment]
Because Mesos just uses the JNI call AttachCurrentThread(), the context class loader in the callbacks should always be the bootstrap class loader (this is what I meant by "default class loader", but that was unclear), and it is currently not possible to have Mesos callbacks start with any other class loader. I didn't think about resetting the class loader because I knew the Mesos callback would just DetachCurrentThread(), but we shouldn't depend on that happening going forward, so I added restoring the old class loaders, too.

**Comment by mridulm** [comment]
I have submitted a PR as a hack to attempt to circumvent this issue
entirely - assuming it works, we would not need to do the set/unset stuff.
My worry is about cases where mesos might be used (if not now, then later)
directly/indirectly from other threads which do not necessarily go through
the same codepaths we have patched it for.

Please see https://github.com/mesos/spark/pull/690

**Comment by mateiz** [comment]
Thanks for the fix Charles.

**Pull request merged**
