### PR TITLE
Bagel: Large-scale graph processing on Spark

### PR DESCRIPTION
**Pull request by ankurdave**
Bagel is an implementation of the Pregel graph processing framework on Spark.

Bagel currently supports basic graph computation, combiners, and aggregators. Future work includes support for mutating the graph topology. Tests exist but currently don't run due to a Spark bug.

### CODE REVIEW

**Comment by tjhunter** [comment]
I would recommend you refactor your code before merging, it is always harder / less tempting to do after.

**Comment by mateiz** [comment]
This looks great, Ankur, except for two naming things: can you change the package name from bagel to spark.bagel, and can you rename the Pregel class to Bagel?

**Comment by ankurdave** [comment]
Sure, I've done so.

**Comment by mateiz** [comment]
Looks great, thanks. The one thing I should add is that maybe you should write a README documenting the examples, or a wiki page (and put a comment in the code pointing to this location).

**Pull request merged**
