### PR TITLE
Ensure that scripts correctly follow symbolic links to determine the framework directory

### PR DESCRIPTION
**Pull request by ianbuss**
Often it may be desirable for packaged versions to create symbolic links to the executor scripts. As they currently stand, the scripts will mis-identify the framework directory using `dirname` to be the directory in which the symlink resides.

The pull request uses a python one-liner as `readlink`'s behaviour can be platform dependent.

### CODE REVIEW

**Comment by jey** [comment]
Jenkins, please test this.

**Comment by pwendell** [comment]
Jenkins, test this please

**Comment by pwendell** [comment]
Unfortunately we can't assume the driver has python installed. Could you give an example of a case where the current approach fails?

**Comment by ianbuss** [comment]
An example use case: packaging conventions often result in symbolic links to executables being placed in `/usr/bin` or similar, sometimes via `/etc/alternatives`. A straight symlink in these cases breaks spark's executor scripts. I suppose it might be argued it should be up to the package author for the particular system to provide a wrapper around the executor scripts to call the script correctly. In fact, I've just discovered this is the approach taken by those adding Spark to Bigtop: https://github.com/apache/bigtop (see lines 148-164 of https://github.com/apache/bigtop/blob/master/bigtop-packages/src/common/spark/install_spark.sh in particular).

I also agree that it shouldn't be assumed that python is installed and that, if any, a "pure bash" solution is desirable.

In view of these points it might be worth dropping this PR and folding it into any work done on SPARK-665.

**Comment by mateiz** [comment]
I actually don't think we should be running spark-executor through the system PATH. Jobs will be configured with a path to Spark. If you do want to run them through the system PATH, maybe just install a script there that cds into the right directory and calls our existing spark-executor? That way we don't need Python and such.

**Comment by mateiz** [comment]
(basically the script in /usr/bin would just say `<SPARK_HOME>/spark-executor "$@"`)

**Comment by ianbuss** [comment]
Agreed. Looking into it further, packages built around other frameworks (e.g. Hadoop) also provide wrapper scripts. Am closing the PR. Thanks for the comments.

**Pull request closed without merging**
