### PR TITLE
Make PySpark AccumulatorParam an abstract base class

### PR DESCRIPTION
**Pull request by JoshRosen**
This commit makes AccumulatorParam an abstract base class, using the [abc](http://docs.python.org/2/library/abc.html) module.  This allows us to use epydoc to document this interface.  I also fixed an epydoc formatting issue in SparkContext.accumulate().

### CODE REVIEW

**Comment by mateiz** [comment]
Looks good, but don't you need to change the doctest that creates a VectorAccumulatorParam too?

By the way, it would be nice to add a small section on this in the Python documentation page (maybe with that vector example).

**Comment by JoshRosen** [comment]
Regarding the Python documentation, how much content do you want to duplicate between the Scala / Java / Python programming guides?  The Java programming guide doesn't provide any examples of accumulators or broadcast variables and the Scala one doesn't explain how to implement custom accumulators.

**Comment by JoshRosen** [comment]
Cloudpickle seems to have problems when serializing AccumulatorParam subclasses, so I stopped using ABCMeta.

**Comment by mateiz** [comment]
I would err on the side of including more in the docs, not less. We can add AccumulatorParam in the Scala ones too eventually (but it doesn't have to be in this pull request).

**Comment by mateiz** [comment]
Thanks Josh!

**Pull request merged**
