### PR TITLE
Remove unused addIfNoPort.

### PR DESCRIPTION
**Pull request by stephenh**
Was reading around the new host/port code and noticed this was unused.

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by stephenh** [comment]
Huh. Seems odd that the tests would have failed for this? The string "addIfNoPort" does not exist anywhere in the spark repo, AFAICT, and if it did, it should result in a compile failure, not the tests timing out...

**Comment by rxin** [comment]
Our Jenkins has been flaky lately... it complains almost every time a new pull request comes.

Jenkins, test this please.

Jenkins, test this again please.

**Comment by jey** [comment]
The root cause is a non-deterministic hang in the `DistributedSuite` tests.

**Comment by rxin** [comment]
But the error message seems to suggest it failed in compilation?

**Comment by jey** [comment]
When I click the link that Jenkins posted and select "console output" from the left-hand menu, I'm taken [here](https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/67/console), and it looks like it is hanging sometime after completing `ShuffleSuite` (probably during `DistributedSuite`?).

**Comment by rxin** [comment]
Ah ok - because the message says

```
Build timed out (after 90 minutes). Marking the build as aborted.
Build was aborted
Recording test results
Finished: ABORTED
```

I actually thought it was running the build itself rather than running the tests. 

How did you tell it was running Shuffle or Distributed? Neither appeared in the log. Did you figure it out just by looking at the log output and pattern-matching the output?

**Comment by jey** [comment]
There's a tiny "Full Log" link at the top of the "Console Output" page

**Comment by mridulm** [comment]
addIfNoPort used to be relevant before the move to executorId - you are
right, it is not used anymore.

Regards,
Mridul

**Comment by mateiz** [comment]
Good catch, going to merge it then.

**Pull request merged**
