### PR TITLE
Re-add removed dependency to fix build under Hadoop 0.23.9

### PR DESCRIPTION
**Pull request by jey**
This kludge, removed in ff6f1b0500a9a75b61c225f3dc80d4026e98bcd5, is actually needed to convince SBT into successfully building with Hadoop 0.23.9.

The root cause is some differences in error handling between Ivy2 and Maven when parsing internally-inconsistent POM files such as the one for commons-daemon.

### CODE REVIEW

**Comment by markhamstra** [comment]
Sorry, Jey.  Which hadoop versions actually needs this?

And the meta question: Do we want to continue to support those versions?

**Comment by jey** [comment]
0.23.9

**Comment by jey** [comment]
Also affects 2.0.4 as documented in https://issues.apache.org/jira/browse/HADOOP-9407

**Comment by mateiz** [comment]
Yeah, unfortunately I think we have to keep this in here. As far as I can tell, 0.23.9 is still the latest stable release on the 0.23 branch.

**Comment by markhamstra** [comment]
How about adding a comment and link to the JIRA issue so that we are not tempted to remove it again?

**Comment by jey** [comment]
@markhamstra: Good idea, done.

**Comment by mateiz** [comment]
Cool, merging this.

**Pull request merged**
