### PR TITLE
Shuffle fixes and cleanup

### PR DESCRIPTION
**Pull request by shivaram**
This set of patches contains fixes for issues uncovered while debugging a large shuffle using netty (SPARK-757).  It contains two major groups of changes:

Netty shuffle fetcher changes:
a. FileClient now uses a connection timeout that can be set using a flag. Default is 60s.
b. Errors during a shuffle fetch are now handled correctly -- We use a variable to track if the callback for adding a fetch result has been invoked and add a failed result (with size -1) if the fetch failed.
c. Minor cleanup of BlockFetcherIterator to handle zero-sized local and remote blocks.

DiskStore changes:
a. The JavaSerializer adds a 9-byte header on initialization which is bad if a file is otherwise empty during a large shuffle. This patch postpones the opening of the file until the first write happens in the DiskBlockWriter.
b. if a ShuffleMap task is rescheduled on the same machine as a previously failed task, we may have a partial shuffle file present. This change deletes a shuffle file if it already exists.

Thanks to @etrain for help with debugging.

### CODE REVIEW

**Comment by mateiz** [comment]
Jenkins, this is ok to test

**Comment by mateiz** [comment]
This looks good -- thanks Shivaram and @etrain. Just going to wait for Jenkins to test it.

**Comment by shivaram** [comment]
Can somebody ask Jenkins to retest this ?

**Comment by rxin** [comment]
Jenkins, retest this please.

**Comment by pwendell** [comment]
Jenkins, test this please.

We can ask, not sure it will work! Jenkins is still a bit unstable.

**Comment by andyk** [comment]
Jenkins retest this please (made another change to Jenkins config, trying again)

**Comment by shivaram** [comment]
Jenkins, retest this please.

**Comment by pwendell** [comment]
Jenkins, test this please

**Comment by mateiz** [comment]
Not sure what's going on with Jenkins, so I've tested this manually and merged it. It seems like the pull request builder is broken. There's an option on the UI to upgrade the Jenkins GitHub plugin but I'm not sure it will help.

**Pull request merged**
