### PR TITLE
Adding new download instructions

### PR DESCRIPTION
**Pull request by pwendell**

### CODE REVIEW

**Comment by pwendell** [comment]
I updated this just now to reflect the templated versions. I also changed the wording a bit.

**Comment by mateiz** [comment]
Thanks but I think this is too long for an overview page. Just say "this documentation corresponds to version X" and they can figure out how to get others. Also, cut the part about Git.

**Comment by pwendell** [comment]
sure now this just says the version and the downloads page.

**Comment by mateiz** [comment]
OK, thanks.

**Pull request merged**
