### PR TITLE
Merge Akka reference.conf files in sbt assembly task

### PR DESCRIPTION
**Pull request by JoshRosen**
This fixes an issue when running Spark from the jar generated by the sbt `assembly` task.

To reproduce the issue:

``` java
import spark.SparkContext;

public class Test {
    public static void main(String[] args) {
        new SparkContext("local", "test");
        System.exit(0);
    }
}
```

Place this code in a file (but not in the root of the `SPARK_HOME` directory), then compile and run it against the assembly jar:

```
$ javac -cp ../core/target/spark-core-assembly-0.6.0-SNAPSHOT.jar Test.java 
$ java -cp ../core/target/spark-core-assembly-0.6.0-SNAPSHOT.jar:. Test
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'
    at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:115)
    at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:135)
    at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:140)
    at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:108)
    at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:146)
    at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:188)
    at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:116)
    at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:429)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:103)
    at spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:36)
    at spark.SparkEnv$.createFromSystemProperties(SparkEnv.scala:58)
    at spark.SparkContext.<init>(SparkContext.scala:71)
    at spark.SparkContext.<init>(SparkContext.scala:55)
    at Test.main(Test.java:5)
```

This issue is caused by the way that Akka `reference.conf` files are handled in the `assembly` task; the commit copies the solution provided by the Akka Team Blog: http://letitcrash.com/post/21025950392/howto-sbt-assembly-vs-reference-conf.

### CODE REVIEW

**Comment by mateiz** [comment]
Woah, that's pretty ugly, but I guess we have to do it. I guess this reference.conf stuff was not a problem before because we weren't using Akka.

**Comment by ijuma** [comment]
No need for all this ugly code. Use a newer sbt-assembly. See http://letitcrash.com/post/21706121997/follow-up-sbt-assembly-now-likes-reference-conf

**Comment by JoshRosen** [comment]
It turns out that we're already using sbt-assembly 0.8.3.  The default `mergeStrategy` used by sbt-assembly should do the right thing for `reference.conf`, but it was not applied because commit ede615d7 added a custom `mergeStrategy` that did not extend the default.

The default `mergeStrategy` fails when trying to deduplicate `javax/servlet/SingleThreadModel.class`, which is probably why the custom `mergeStrategy` was added:

```
[info] Merging 'javax/servlet/SingleThreadModel.class' with strategy 'deduplicate'
[error] {file:/Users/josh/Documents/programming/spark/spark/}repl/*:assembly: deduplicate: different file contents found in the following:
[error] /Users/josh/Documents/programming/spark/spark/lib_managed/jars/javax.servlet/servlet-api/servlet-api-2.5.jar:javax/servlet/SingleThreadModel.class
[error] /Users/josh/Documents/programming/spark/spark/lib_managed/jars/org.mortbay.jetty/servlet-api-2.5/servlet-api-2.5-6.1.14.jar:javax/servlet/SingleThreadModel.class
[error] /Users/josh/Documents/programming/spark/spark/lib_managed/jars/org.mortbay.jetty/servlet-api/servlet-api-2.5-20081211.jar:javax/servlet/SingleThreadModel.class
[error] {file:/Users/josh/Documents/programming/spark/spark/}core/*:assembly: deduplicate: different file contents found in the following:
[error] /Users/josh/Documents/programming/spark/spark/lib_managed/jars/javax.servlet/servlet-api/servlet-api-2.5.jar:javax/servlet/SingleThreadModel.class
[error] /Users/josh/Documents/programming/spark/spark/lib_managed/jars/org.mortbay.jetty/servlet-api-2.5/servlet-api-2.5-6.1.14.jar:javax/servlet/SingleThreadModel.class
[error] /Users/josh/Documents/programming/spark/spark/lib_managed/jars/org.mortbay.jetty/servlet-api/servlet-api-2.5-20081211.jar:javax/servlet/SingleThreadModel.class
[error] Total time: 93 s, completed Aug 1, 2012 11:04:10 PM
```

Adding `case "reference.conf" => MergeStrategy.concat` to our `mergeStrategy` solves the problem.

**Comment by mateiz** [comment]
Ah, makes sense. Do you mind sending another pull request with that then?

**Pull request merged**
