### PR TITLE
Replacing the native lzf compression code with ning's lzf library

### PR DESCRIPTION
**Pull request by jhartman**
Hi Matei (and others),

I replaced the native code with ning's apache 2.0 compression library. This way, spark doesn't have to maintain the LZF code, lzf compression can be used in places (like corporate environments) where native code is a no-go for deployment issues, and the JNI performance penalty doesn't have to be paid.

Code compiles and tests pass.
- Josh

### CODE REVIEW

**Comment by mateiz** [comment]
This looks great, but I have one minor request: Can you include the license for Ning's LZF library in its directory in third_party, just for future reference?

**Comment by jhartman** [comment]
There you are. I'll merge this into the sbt branch soon as well.

**Comment by mateiz** [comment]
Thanks Josh. I've merged this into master. Do you want to add another pull request for sbt or should I merge it myself?

**Comment by jhartman** [comment]
I'll send a pull request for sbt. I'm not sure when it'll be ready - I really haven't started on it yet.

By the way, it looks like Spark doesn't have an actual license. What is the license(s) you plan on using?
- Josh

**Comment by mateiz** [comment]
I'm going to put it under the BSD license. I'll add that soon. In the long term, after more core functionality is done, I'm also thinking of putting Spark in the Apache Incubator.

(All the projects we work on at Berkeley get released under BSD or BSD-like licenses as part of our agreement with our industry sponsors.)

**Pull request merged**
