### PR TITLE
Fixing count() in Spark Streaming

### PR DESCRIPTION
**Pull request by mcnamaras**
Previously when there was no data count() would not emit anything downstream.  This pull request fixes it so that under this condition 0 will be emitted.

### CODE REVIEW

**Comment by mcnamaras** [comment]
One question I just had about my implementation- Will the ConstantInputDStream RDD stick around, or will it get removed by the cleaner?

**Comment by tdas** [comment]
The ConstantInputDStream RDD will get removed. So it should not be used for anything other than simple testing.

**Comment by tdas** [comment]
I think its better to implement this fix using transform operation rather than using constantinputdstream. In the transform operation, each mapped RDD can be unified with an special RDD created using makeRDD(...) . Note that the special RDD must be created every time and not reused, other wise it will have the same problem as the constantinputdstream.

**Comment by mcnamaras** [comment]
That makes sense. I will look into reformulating it with a transform.  Thanks!

**Comment by tdas** [comment]
Any update on this?

**Comment by mcnamaras** [comment]
Hey TD!  So sorry, I have been sidetracked with travel and other things.  I will try to get to this very soon.

**Comment by mcnamaras** [comment]
Please let me know how this looks.  Thanks!

**Comment by pwendell** [comment]
Jenkins, test this please

**Pull request merged**
