### PR TITLE
Fix PySpark unit tests on Python 2.6

### PR DESCRIPTION
**Pull request by JoshRosen**
This commit allows PySpark's unit tests to run on Python 2.6.  A number of Linux distros (including CentOS 6.4, which powers the AMP Lab's Jenkins servers) still use Python 2.6 by default.

I also added logging to the `run-tests` script to redirect the test output into a file.

I updated the Jenkins pull request builder to run these tests, so you should see PySpark output at the end of the test log.

### CODE REVIEW

**Comment by mateiz** [comment]
Jenkins, please retest this

**Comment by mateiz** [comment]
Looks like the test that failed is one that can actually occasionally fail since it uses some ephemeral ports, but let's retry it.

**Comment by JoshRosen** [comment]
Jenkins, retest this please.

**Comment by mateiz** [comment]
Josh, is Jenkins actually going to run these tests? Or maybe the pull-request builder isn't set up for it?

**Comment by JoshRosen** [comment]
@mateiz I modified the Jenkins pull-request builder to run the PySpark tests, and I'll apply the same change to the other Jenkins configurations.  You can see the test output at the end of https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/589/console

There are a few Jenkins improvements that I could make, including more verbose doctest/unittest output and fancier reporting of Python test results, but this seems like a decent start for now.

**Comment by mateiz** [comment]
Ah, got it. I was thinking they'd show up in Jenkins' test report. I'll merge this in then.

**Pull request merged**
