### PR TITLE
Add an Avro dependency to REPL to make it compile with Hadoop 2

### PR DESCRIPTION
**Pull request by mbautin**
Without this, I was getting the following compilation error:

```
error: error while loading Path, Missing dependency 'class org.apache.avro.reflect.Stringable', required by /Users/mbautin/.m2/repository/org/apache/hadoop/hadoop-common/2.0.0-cdh4.1.2/hadoop-common-2.0.0-cdh4.1.2.jar(org/apache/hadoop/fs/Path.class)
/wd/spark/repl/src/main/scala/spark/repl/ExecutorClassLoader.scala:37: error: org.apache.hadoop.fs.Path does not have a constructor
          fileSystem.open(new Path(directory, pathInDirectory))
```

### CODE REVIEW

**Comment by mateiz** [comment]
Why does this not come from the hadoop2 dependency? I've compiled it with Hadoop 2 before.

**Comment by mbautin** [comment]
I think this is because a transitive dependency on an older version of Avro was introduced through Streaming, which did not include some classes required by `org.apache.hadoop.fs.Path`.

**Comment by mateiz** [comment]
Oh, I see. That does make sense. Going to merge it.

**Comment by mateiz** [comment]
So by the way, does "core" work okay or should we put the dependency there?

**Pull request merged**
