### PR TITLE
Fix issues with streaming test cases after yarn branch merge

### PR DESCRIPTION
**Pull request by mridulm**
This is an attempt to isolate and resolve issues which surfaced with streaming testcases after yarn branch merge.

### CODE REVIEW

**Comment by mridulm** [comment]
There are a few log messages added which we will remove once it is confirmed that the bug is resolved.
I am not able to reproduce the issue after this patch (the mail I had sent earlier had incomplete diffs, apologies !).

But I am trying on other machines in case it is just a local issue with not reproducing the bug.

Regards,
Mridul

**Comment by mridulm** [comment]
This is work in progress, please do not merge it yet.

**Comment by mateiz** [comment]
Cool, thanks for looking at it. This does seem like a good fix. It also seems to solve the issues on my machine, though I'll keep testing it to make sure.

**Comment by mridulm** [comment]
There seems to be still some issue, I am trying to nail it down.
Will keep this pull request updated.

Apologies for introducing this issue !
Regards,
Mridul

**Comment by mridulm** [comment]
Hi Matei,

  I cant seem to find any other reproducible issue with the codebase.
I did see a failure once out of about 50 tries, but unfortunately, it was is not reproducible and the log messages were not sufficient to debug it.

As we discussed, that problem might be elsewhere actually ... I suspect related to serialization of a DStream whose state might be changing while serialization was happening (which is not something we touched in yarn merge).

For now, I think this PR is good to go pending your review. In case I find a reproducible testcase, I will definitely try to debug this issue more.

Regards,
Mridul

**Comment by mateiz** [comment]
Thanks Mridul. I'll keep looking into it as well, but these are good fixes to have.

**Pull request merged**
