### PR TITLE
Cleaned up scheduler code to have more coherent comments and <100 char lines.

### PR DESCRIPTION
**Pull request by kayousterhout**

### CODE REVIEW

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by rxin** [comment]
Jenkins, test this please.

**Comment by mateiz** [comment]
Hey Kay, just FYI, I've been working on this stuff pretty extensively in a branch (https://github.com/mateiz/spark/tree/sched-improvements), so it's probably best not to change it too much. Some of those comments/functions are just gone in my branch. That said, I can merge this in and keep the ones that I didn't change.

You can view my changes here: https://github.com/mateiz/spark/compare/sched-improvements (expand the commit messages there for a summary). They simplify the scheduler code quite a bit and pass the unit tests and such but I haven't yet tested them extensively on clusters.

**Comment by kayousterhout** [comment]
Ah ok seems like it makes sense to just hold off on this then since your
branch changes/deletes most of this code.  Sorry about that!

**Comment by mridulm** [comment]
Ah ! This is an interesting branch.
I would have loved to get my hands on it ... sigh.

Looking forward to final commit from this.

Regards,
Mridul

**Pull request closed without merging**
