### PR TITLE
Send Task results through the block manager when larger than Akka frame size (fixes SPARK-669).

### PR DESCRIPTION
**Pull request by kayousterhout**
This change requires adding an extra failure mode: tasks can complete
successfully, but the result gets lost or flushed from the block manager
before it's been fetched.

Thanks Josh for writing the original version of this patch!

### CODE REVIEW

**Comment by pwendell** [comment]
I had to kill this test because it had been running for more than 1 hour. Checkout the output here:

https://amplab.cs.berkeley.edu/jenkins/job/SparkPullRequestBuilder/604/console

**Comment by mateiz** [comment]
Thanks for implementing this, Kay! I haven't had a chance to read through it yet but I'll take a close look early this week.

**Comment by kayousterhout** [comment]
Cool sounds good. Also, "TaskResultGetter" is a bad name -- Patrick
suggested "taskResultFetcher" or "taskResultResolver" but will wait to
change it until you look at it in case you have a better name idea.

**Comment by kayousterhout** [comment]
I updated this to master and also implemented Patrick's naming suggestion

**Comment by rxin** [comment]
Closing this one since it has been resubmitted to the asf repo

**Pull request closed without merging**
