### PR TITLE
Regression: default webui-port can't be set via command line "--webui-port" anymore

### PR DESCRIPTION
**Pull request by ghost**
This fixes the old behaviour broken during the transition to the new UI code

### CODE REVIEW

**Comment by ghost** [comment]
Thanks to Michael Parkin for the fix's idea!

**Comment by pwendell** [comment]
Hey @cos - thanks for catching this! The underlying problem is that both MasterArguments and MasterWebUI try to calculate the correct port, deal with defaults, etc.

This patch does fix the issue, but could you amend it to actually remove the redundancy?

I'm suggesting that you make the ui port no longer optional in the MasterWebUI constructor and remove the DEFAULT_PORT value in that class. Leave that logic of deciding the port number entirely to MasterArguments.

**Comment by ghost** [comment]
Makes sense. I will re-do the patch tomorrow. I think the whole issue is caused by a somewhat over-complication of the data flow in this part and the simplification you just proposed would be very welcome.

**Comment by ghost** [comment]
Updated patch with simplified logic. I still am not sure why there are three different way to specify the alternative port, but I think it can be left along for now.

**Comment by pwendell** [comment]
Hey @cos - once your patch goes in we'll have the system property `master.ui.port` as the single way to do this, and it is handled by MasterArguments and nowhere else.

You said there are three ways to do this - what are the other two? We should definitely simplify this as much as possible.

**Comment by ghost** [comment]
command line is the second way
shell environment variable is yet another one ;)

And to be honest - these two above look valid both for quick cli runs and using in the linux packaging. The sys.prop seems like an excess to me, to be honest.

**Comment by pwendell** [comment]
Ah, point taken. It's a bit cluttered to have a system property and a command line argument (the env variable is just an intermediate config option that gets translated into a CL arg). 

In any case, this looks good to me. Maybe @mateiz could take a look and merge it?

**Comment by pwendell** [comment]
Jenkins, test this please.

**Comment by mateiz** [comment]
Looks good, thanks Cos!

**Pull request merged**
