### PR TITLE
Fix setting of SPARK_EXAMPLES_JAR

### PR DESCRIPTION
**Pull request by jey**
This PR moves the setting of the `SPARK_EXAMPLES_JAR` environment variable back to the `run` script because it has no effect when set in the `compute-classpath.sh` script (which is run in a subshell whose environment is then immediately discarded).

### CODE REVIEW

**Comment by mateiz** [comment]
Hey Jey, this is good, but you'll have to do it in the Windows version of the scripts as well. You can spin up a Windows instance on EC2 and log into it with remote desktop to try it, or maybe run a VM.

**Comment by jey** [comment]
Matei, this bug isn't present in the Windows scripts as far as I can tell. The `run2.cmd` script seems like it sets `SPARK_EXAMPLES_JAR` correctly.

**Comment by mateiz** [comment]
Ah, good point!

I noticed one other issue though, which is that $EXAMPLES_DIR won't be set if we're in a "release" version of the system (see the if statement above). Maybe you should move this stuff within the if statement?

**Comment by jey** [comment]
Oops, yeah. Fixed

**Comment by mateiz** [comment]
Thanks, merged this.

**Pull request merged**
