### PR TITLE
Add a public method getCachedRdds to SparkContext

### PR DESCRIPTION
**Pull request by velvia**
Pretty self explanatory - adds a method to SparkContext to return the immutable map of RDD ID's to RDDs themselves.   Amongst other uses, for our job server, this allows two different jobs submitted as separate JARs to obtain cached RDDs just by using a method from the SparkContext.

### CODE REVIEW

**Comment by mateiz** [comment]
Jenkins, this is ok to test

**Comment by mateiz** [comment]
Hey, a couple of comments on this:
1. It would be better to clone the persistentRdds hashmap instead of just casting it to an immutable Map, because underneath it will still change over time as we remove old RDDs. I believe you can do immutable.Map() ++ persistentRdds.
2. For the unit tests, instead of adding them to RDDSuite and having them depend on the number of cached RDDs before, make a new test suite or find one that doesn't reuse the SparkContext across tests. We have a trait for that.

**Comment by rxin** [comment]
Thanks. In addition to Matei's comment, it would also be better for this to be called getPersistentRdds instead of getCachedRdds. In general we are moving the terminology from "cache" to "persistent".

**Comment by ryanlecompte** [comment]
@mateiz, nice catch for returning a proper `scala.collection.immutable.Map` instead of the casting. I'd also suggest perhaps adding a `toMap` method to `TimestampedHashMap` that returns a proper `scala.collection.immutable.Map` so that we can reuse it elsewhere. This is common for other maps in the Scala collections library, too, e.g.:

``` scala
scala> scala.collection.immutable.TreeMap(1 -> 2).toMap
res2: scala.collection.immutable.Map[Int,Int] = Map(1 -> 2)

scala> scala.collection.mutable.HashMap(1 -> 2).toMap
res3: scala.collection.immutable.Map[Int,Int] = Map(1 -> 2)
```

**Comment by mateiz** [comment]
Yeah, a `toMap` is a good idea.

**Comment by velvia** [comment]
Thanks for all the great feedback guys.  I'm almost done with the changes.

**Comment by mateiz** [comment]
Jenkins, test this please

**Comment by mateiz** [comment]
LGTM, thanks.

**Pull request merged**
