### PR TITLE
Make Executor fields volatile since they're read from the thread pool.

### PR DESCRIPTION
**Pull request by stephenh**
A few times now I've had clusters fail due to stack trackers like below, where Kryo can't load my spark.kryo.registrator class. It's really odd because sometimes it works, sometimes it doesn't.

Looking at the code, I'm wondering if Executor:89:

```
      Thread.currentThread.setContextClassLoader(urlClassLoader)
```

Was reading a stale value (null), and so the context class loader wasn't being set.

I'm running this patch on some jobs now to see if it helps, but the failure is random, so just a few good jobs isn't a guarantee. But either way, it seems like these fields are access in a multithreaded way, so should be marked as volatile.

Right?

```
13/02/28 07:35:44 INFO cluster.TaskSetManager: Loss was due to java.lang.ClassNotFoundException: com.MyRegistrar
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at spark.KryoSerializer.createKryo(KryoSerializer.scala:209)
    at spark.KryoSerializer$$anon$1.initialValue(KryoSerializer.scala:111)
    at spark.KryoSerializer$$anon$1.initialValue(KryoSerializer.scala:110)
    at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:141)
    at java.lang.ThreadLocal.get(ThreadLocal.java:131)
    at spark.KryoSerializer.newInstance(KryoSerializer.scala:216)
    at spark.broadcast.HttpBroadcast$.read(HttpBroadcast.scala:127)
    at spark.broadcast.HttpBroadcast.readObject(HttpBroadcast.scala:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:974)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1848)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at scala.collection.immutable.$colon$colon.readObject(List.scala:435)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:974)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1848)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at scala.collection.immutable.$colon$colon.readObject(List.scala:435)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:974)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1848)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at scala.collection.immutable.$colon$colon.readObject(List.scala:435)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:974)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1848)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at spark.JavaDeserializationStream.readObject(JavaSerializer.scala:23)
    at spark.scheduler.ResultTask$.deserializeInfo(ResultTask.scala:42)
    at spark.scheduler.ResultTask.readExternal(ResultTask.scala:105)
    at java.io.ObjectInputStream.readExternalData(ObjectInputStream.java:1791)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1750)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at spark.JavaDeserializationStream.readObject(JavaSerializer.scala:23)
    at spark.JavaSerializerInstance.deserialize(JavaSerializer.scala:45)
    at spark.executor.Executor$TaskRunner.run(Executor.scala:98)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
```

### CODE REVIEW

**Comment by ryanlecompte** [comment]
These variables shouldn't really need to be marked as @volatile. From my
cursory view of the code, they are only assigned once in the initialize()
method. Also, the threads that end up reading these variables are created
after the fields are assigned. It would be a problem if somehow a spawned
thread could read these variables BEFORE they are first assigned to, then
using @volatile or other synchronization would be required so that the
latest values are properly published to those threads.

**Comment by stephenh** [comment]
@ryanlecompte Yeah, I know the field writes happen before the reads in wall clock time, but I wasn't 100% positive there is a JVM "happens-before" occurring that would keep the spawned threads from seeing the old value. Is the assumption that creating the ThreadPool (or it creating the threads) causes that to happen?

**Comment by ryanlecompte** [comment]
My understanding from JCIP is that you only need @volatile or manual
synchronization if you end up mutating a shared variable that your spawned
thread is referencing _after_ it's fully created. The typical example would
be having a "stopped" boolean that your spawned thread constantly reads to
know whether or not it should gracefully stop running. The JVM won't
guarantee that the spawned thread will see the latest value if it's written
to by another thread (e.g., setting "stopped" to true) without proper
synchronization or use of @volatile. However, my current understanding of
Spark internals is limited, so it might still be worth running your jobs
with these modifications and see if the problem suddenly goes away.

On Thu, Feb 28, 2013 at 10:25 AM, Stephen Haberman <notifications@github.com

**Comment by stephenh** [comment]
@ryanlecompte Yeah, I agree this sounds fishy, but so far I can't see where else this non-determinism would be coming from. As an alternative approach, I just pushed a change which gets rid of the vars by removing the lazy initialization of the Executor.

**Comment by stephenh** [comment]
Well. This doesn't seem to have been it, still getting the random ClassNotFoundException for my registrar.

**Comment by rxin** [comment]
How did you set your registrator? Is it with system property?

**Comment by stephenh** [comment]
Yeah:

```
    System.setProperty("spark.serializer", "spark.KryoSerializer")
    System.setProperty("spark.kryo.registrator", classOf[MyRegistrar].getName)
```

What's odd is usually just rerunning the job (new EMR cluster, same jars/same config) works.

**Comment by rxin** [comment]
How is this code block executed versus initializing the spark context? I had a problem previously in which spark context was part of a static block in an object, which doesn't get initialized until the SparkContext was ...

**Comment by stephenh** [comment]
Well. I am still having this issue.

Nonetheless, I think this pull request is a nice clean-up of its own accord--instead of having Executor in an partially created state, it just waits until the RegisteredExecutor message comes in with all of the info we need (hostname, properties), and then creates the Executor.

If you don't feel this is an improvement, that's fine; let me know and I'll close the pull request.

**Comment by mateiz** [comment]
I think the cleanup is good; thanks for the fix.

**Pull request merged**
